### ISSUE TITLE
Installer issues

### ISSUE THREAD

**Issue by JustYuuto** [JustYuuto/deezer-discord-rpc#14]
Hi,

Recently you might had an installer issue saying that the program is already running but it's not. I'm running into the same problem and I don't know what is the source problem. I want to know if anyone else is having the problem, if yes please reply to this issue with your system version.

A temporary fix for getting it working is running these commands (in **a command prompt**, **not** PowerShell) for deleting the app folders (note that will delete the config and log you out of Deezer on the app): 
```bash
del /F /S /Q %appdata%\deezer-discord-rpc
del /F /S /Q %localappdata%\deezer-discord-rpc-updater
del /F /S /Q %localappdata%\Programs\deezer-discord-rpc
```

If you don't want to use commands or don't know how to use them: https://github.com/JustYuuto/deezer-discord-rpc/issues/14#issuecomment-1674667104

Then just relaunch the installer you've downloaded.

**Comment by Zalk0** [comment]
Hello,

I have the same issue on Windows 10 22H2, I encountered it with the update to 1.1.17 and now again to 1.1.18. I don't remember before but it may be because it hasn't been long since I came across your project and I began using it with 1.1.16 🤔

I deleted the folders and launched the installer afterwards and it worked ( I did the same thing before for upgrading to 1.1.17).
