### ISSUE TITLE
1.2.4 seems to working not properly 

### ISSUE THREAD

**Issue by weplick** [JustYuuto/deezer-discord-rpc#34]
Hi, so I tried to install latest 1.2.4 today and the app is running fine, but there's no application tray so I don't know how to get RPC and it's not showing any status in DIscord
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/167795779/73047b0c-de92-4c48-8dc6-7ddc77f11d99)
I'm running on win10x64 22h2
Also while music is playing if I tap on Exit button. music is still playing and the only way to stop is to kill Deezer Discord RPC.exe because no appliacation tray is available. Or should I turn it on somewhere else? 
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/167795779/d8d820b2-e69e-49f6-ba02-eb595f2c1e7b)
Installed running as admin
Please provide any solution to it

**Comment by JustYuuto** [comment]
Hi, thank you for reporting the problem :) It seems that I messed up when making the exe for this version. Anyway it should be fixed in the [latest version](https://github.com/JustYuuto/deezer-discord-rpc/releases/tag/1.2.5)

For the rpc try restarting your Discord client and/or read https://github.com/JustYuuto/deezer-discord-rpc/wiki/Troubleshooting#nothing-appears-on-my-profile

**Comment by weplick** [comment]
> Hi, thank you for reporting the problem :) It seems that I messed up when making the exe for this version. Anyway it should be fixed in the [latest version](https://github.com/JustYuuto/deezer-discord-rpc/releases/tag/1.2.5)
> 
> For the rpc try restarting your Discord client and/or read https://github.com/JustYuuto/deezer-discord-rpc/wiki/Troubleshooting#nothing-appears-on-my-profile

Yes, now after update all is working, thanks for fix
